In [1]:


from jax import numpy as jnp
from flax import linen as nn
from tensorflow_probability.substrates.jax import distributions as tfd
import jax.random as rnd


2022-04-20 13:54:25.892091: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


In [7]:
shape = (2, 5)
mean0 =jnp.zeros(shape)
std1 =jnp.ones(shape) + 1.
dist0 = tfd.Normal(mean0, std1)
z = dist0.sample(seed=rnd.PRNGKey(1))
print(z)

key = rnd.PRNGKey(1)
key1, key2 = rnd.split(key, 2)
mean = rnd.normal(key1, shape)
std = jnp.abs(rnd.normal(key2, shape))
dist = tfd.Normal(mean, std)
log_prob = dist.log_prob(mean)  # HAS BEEN SUMMED ACROSS THE BATCH! 
print(log_prob)
kl_div = dist.kl_divergence(dist0)
print(kl_div)

[[ 1.38161    -0.97488207 -2.311578    0.24216926 -0.39196864]
 [-1.0157531   1.8313731   3.41936    -0.73498833  0.28631377]]
[[-0.3780179  -0.39258528  0.55717444 -1.5076014  -0.770799  ]
 [ 1.7391242  -0.9172018   0.7383628   0.5731615  -1.4756505 ]]
[[0.82824457 0.83716345 1.6868956  0.03882546 0.93719566]
 [3.0547671  0.34374455 1.8632145  1.9663383  0.39925566]]


[[ 0.9087967  -0.040249    0.17204419 -1.6576358   0.353745  ]]
[[0.21586019 0.55759454 0.52032065 0.33626488 2.129472  ]]
[[-0.9189385 -0.9189385 -0.9189385 -0.9189385 -0.9189385]]
[[0.42138612 0.3183497  0.32184708 0.66161674 0.3337891 ]
 [0.42138612 0.3183497  0.32184708 0.66161674 0.3337891 ]
 [0.42138612 0.3183497  0.32184708 0.66161674 0.3337891 ]
 [0.42138612 0.3183497  0.32184708 0.66161674 0.3337891 ]
 [0.42138612 0.3183497  0.32184708 0.66161674 0.3337891 ]
 [0.42138612 0.3183497  0.32184708 0.66161674 0.3337891 ]
 [0.42138612 0.3183497  0.32184708 0.66161674 0.3337891 ]
 [0.42138612 0.3183497  0.32184708 0.66161674 0.3337891 ]
 [0.42138612 0.3183497  0.32184708 0.66161674 0.3337891 ]
 [0.42138612 0.3183497  0.32184708 0.66161674 0.3337891 ]]


In [24]:
mean = rnd.normal(key1, shape)
std = jnp.abs(rnd.normal(key2, shape))


prior1 = tfd.Independent(tfd.Normal(jnp.zeros(shape), jnp.ones(shape)))
dist1 = tfd.Independent(tfd.Normal(mean, std))
prior = tfd.Normal(jnp.zeros(shape), jnp.ones(shape))
dist = tfd.Normal(mean, std)
# print(mean, std)



In [25]:
ind_kl = dist1.kl_divergence(prior1)
kl = dist.kl_divergence(prior).sum(-1)

print(ind_kl - kl)

[0.]


In [26]:
print(dist1.log_prob(mean), dist.log_prob(mean))

[-1.4901531] [[ 0.6141858  -0.33481532 -0.26562852  0.17091763 -1.6748126 ]]


In [21]:
print(dist1.event_shape, dist1.batch_shape)

(20,) (10,)
